### PR TITLE
Moodle 401 stable

### PR DESCRIPTION
**Pull request by stantonly**
*** PLEASE DO NOT OPEN PULL REQUESTS VIA GITHUB ***

The moodle.git repository at Github is just a mirror of the official repository. We do not accept pull requests at Github.

See CONTRIBUTING.txt guidelines for how to contribute patches for Moodle. Thank you.

--

### CODE REVIEW

**Comment by stantonly** [comment]
So far, so good as far as getting what I was driven to accomplish, accomplished. I wanted to have a moment where the two titans clashed, moodle and Azure. This was that very accomplishment. However, I must take none of the credit, as it turns out any and all of my input was nothing but a hindrance of a smooth operation. The credit goes out to the auto-bot that we merged into, as I was opening a ton of files hoping that one of them would be like the golden ticket to Wonka's factory. Nope, not even the .yml file I pulled was right. In fact, I don't even know what the hell kind of file was actually used to combine moodle and azure. In fact, I did absolutely nothing now that I think about it, except open a bunch of random, unnecessary files and close them out. But, needless to say, thanks to the bot, we are where we wanted to be. Thank god.

**Comment by stantonly** [comment]
So far, so good as far as getting what I was driven to accomplish, accomplished. I wanted to have a moment where the two titans clashed, moodle and Azure. This was that very accomplishment. However, I must take none of the credit, as it turns out any and all of my input was nothing but a hindrance of a smooth operation. The credit goes out to the auto-bot that we merged into, as I was opening a ton of files hoping that one of them would be like the golden ticket to Wonka's factory. Nope, not even the .yml file I pulled was right. In fact, I don't even know what the hell file was used to combine moodle and azure. In fact, I did absolutely nothing now that I think about it, except open a bunch of files and close them out.l But, needless to say, thanks to the bot, we are where we wanted to be. Thank god.

**Comment by stantonly** [comment]
One more thing, uhh, yeah, I don't know if it's going to reflect on here, the amount of times I opened and closed the merger here in the last couple of minutes. To be honest, I wasn't following any sort of intuition of direction, I was, to be honest, very attracted to the colors of the buttons and framing of these comment boxes when they were open. And when I pushed the close button, I wasn't as 'turned on' by the color scheme, so I reopened. It wasn't until about a 2 or three times of opening and closing and opening again that I realized there's a disclaimer at the top of this page, only a mere couple of inches I supposed from my comment. The disclaimer explicitly not to do what I just did. SO, we'll see how this road goes. Must say, I do fancy the green color. Green for go.

**Comment by andrewnicols** [comment]
Hi,

Thanks for the patch. This repository is only a mirror of the official Moodle git repository at git.moodle.org. We don't deal with pull requests on GitHub but on the Moodle tracker. I'm closing this pull request, please progress it through the Moodle tracker instead.

See http://docs.moodle.org/dev/Process#Fixing_a_bug for more details.

**Pull request closed without merging**
