### PR TITLE
MDL-49309: sort cohorts by name

### PR DESCRIPTION
**Pull request by garykrige**

### CODE REVIEW

**Comment by gjb2048** [comment]
Hi @garykrige - you are wasting your time here as patches will NOT be pulled from GitHub in this manner.  Please start by reading: https://docs.moodle.org/dev/Tracker_guide.

**Comment by gjb2048** [comment]
Then: https://docs.moodle.org/dev/Process

**Comment by garykrige** [comment]
yeah I realise this is a waste of time, but I have not managed with tracker and I was just getting really frustrated with it. Gave up on getting it pulled - such an insignificat change

**Comment by danpoltawski** [comment]
Hi Gary,

I have sorted your issue for peer review in the tracker - sorry that the process is not clear enough. I'm closing this issue now because we can't merge it (this repo is just a mirror of git.moodle.org)

**Comment by burningTyger** [comment]
a general comment since I'm tracking the moodle repo to get updates for moodle shown in my timeline and seeing lots of pull requests closed. Wouldn't it be useful to have one person doing pull requests here on behalf of the official tracker? Most issues don't need further comments and just pushing them forward to the tracker would be a huge time saver for many people that only use Github.

I know that your using your own tracker for a reason but lowering the barrier to contribute would be really great.

**Comment by roelmann** [comment]
No, because that would involve multiple systems and lead to
inconsistencies. Its better to let the HQ team pull any changes through a
single system into their master copies and then let them distuibute this as
a 'public' clone with everything stable and working - at least that's my
feeling.
I don't want the 'public' clone version to start getting caught up with
someone having to commit or reject pulls that people post on there without
them going through the full quality control and integration processes that
are involved in the system at the moment, and that means through the
tracker.
Lowering the barrier for contributions is one thing, but leaving the moodle
git pages open for anyone and everyone to submit pull requests to and
having to have someone trawl through that would not help in my opinion.
Just my 2c as someone who uses github to keep my moodle dev systems upto
date :)

**Comment by andrewnicols** [comment]
Actually, we already do this. Those on the integration team take this role and do typically try to push things forward on the tracker. We attempt to include the patch if at all possible too.

**Comment by danpoltawski** [comment]
We have an existing issue open about improving the process - please contribute there: https://tracker.moodle.org/browse/MDLSITE-3684

**Pull request closed without merging**
